### PR TITLE
update Robotis git sub-module to add BPF-BU and BPF-WA

### PR DESCRIPTION
**Pull request by matthieu-lapeyre**

### CODE REVIEW

**Comment by PirouetteNeroz** [comment]
I have this error when i Clone my depot and it is impossible to merge your pull request

git -c diff.mnemonicprefix=false -c core.quotepath=false clone --recursive https://github.com/Alexandre-lefalher/creature.git C:\Users\Alexandre\Documents\creature
Cloning into 'C:\Users\Alexandre\Documents\creature'...

Submodule 'hardware/robotis_library' (https://github.com/poppy-project/Robotis-library.git) registered for path 'hardware/robotis_library'

Cloning into 'hardware/robotis_library'...

fatal: reference is not a tree: 4117f9dbeb55048c648efcd41019ccda6a4a85ec

Unable to checkout '4117f9dbeb55048c648efcd41019ccda6a4a85ec' in submodule path 'hardware/robotis_library'

Terminé avec des erreurs, voir ci-dessus

Edit:
It is good I created the update because I had some error with the depot

**Comment by matthieu-lapeyre** [comment]
Is it possible to directly merge now ?

**Comment by matthieu-lapeyre** [comment]
Ok you solved the problem meanwhile with this commit https://github.com/Alexandre-lefalher/creature/commit/4170d3b3ecf711671746f71fb1290a82a4d4a554

**Comment by PirouetteNeroz** [comment]
Yes, so normally the problem is solved

**Pull request closed without merging**
